name: project_uas_kelompok_3
version: 1.0.0+1
publish_to: none
description: Projek E-Commerce Kelomppok 3.
environment: 
  sdk: '>=3.3.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images
